# Generated by Django 3.0.2 on 2020-07-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('album', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('rating', models.CharField(choices=[('0.5 / 5.0', '0.5 / 5.0'), ('1.0 / 5.0', '1.0 / 5.0'), ('1.5 / 5.0', '1.5 / 5.0'), ('2.0 / 5.0', '2.0 / 5.0'), ('2.5 / 5.0', '2.5 / 5.0'), ('3.0 / 5.0', '3.0 / 5.0'), ('3.5 / 5.0', '3.5 / 5.0'), ('4.0 / 5.0', '4.0 / 5.0'), ('4.5 / 5.0', '4.5 / 5.0'), ('5.0 / 5.0', '5.0 / 5.0')], max_length=10)),
                ('like', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cover_art_url', models.CharField(max_length=500)),
                ('album_id', models.CharField(max_length=62)),
                ('artist_id', models.CharField(max_length=62)),
            ],
        ),
    ]
