# Generated by Django 3.0.2 on 2020-07-20 21:48

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone
from django.contrib.postgres.operations import HStoreExtension



class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        HStoreExtension(),
        migrations.RemoveField(
            model_name='list',
            name='name',
        ),
        migrations.AddField(
            model_name='list',
            name='albums_info',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='list',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='title_slug',
            field=models.SlugField(default='temp-list-title-slug'),
            preserve_default=False,
        ),
    ]
