# Generated by Django 3.0.2 on 2020-07-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20200720_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='albums_info',
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('album_id', models.CharField(max_length=62)),
                ('artist', models.CharField(max_length=300)),
                ('artist_id', models.CharField(max_length=62)),
                ('cover_art_url', models.TextField()),
                ('lists', models.ManyToManyField(to='lists.List')),
            ],
        ),
    ]
