# Generated by Django 3.0.2 on 2020-07-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_auto_20200720_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='lists',
        ),
        migrations.AddField(
            model_name='list',
            name='lists',
            field=models.ManyToManyField(to='lists.Album'),
        ),
    ]
