# Generated by Django 3.0.2 on 2020-07-21 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20200721_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='lists',
            new_name='albums',
        ),
    ]
