# Generated by Django 3.0.2 on 2020-08-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_auto_20200721_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='list',
            name='title_slug',
            field=models.SlugField(max_length=500, null=True),
        ),
    ]
